### ISSUE TITLE
Rules not granting access

### ISSUE THREAD

**Issue by bborncr** [uhppoted/uhppoted-app-wild-apricot#4] opened 2024-02-13 15:49 UTC
First of all, thanks for this code! I have been testing it using the python and mqtt implementations with a lot of success. Using the Wild Apricot implementation I can't get the access to be granted.

Grules file:

```
// *** GRULES ***

rule Doors "Grants a member access to both doors" {
     when
         member.HasGroup("Doors")
     then
         record.Grant("Front Door");
         record.Grant("Back Door");
         record.Grant("Unused3");
         record.Grant("Unused4");
         Retract("Doors");
}

// *** END GRULES ***

```

ACL output:

```
Card Number     From    To      Back Door       Front Door      Unused3 Unused4
12345678        2024-01-01      2025-01-31      N       N       N       N
12345679        2024-01-01      2025-01-31      N       N       N       N

```

The app connects successfully to Wild Apricot and sees all the members, groups and cards.
There are no errors. The ACL is successfully loaded into the controller but access is "N". Is there something obvious I'm missing?

uhppoted.conf
```
bind.address = 0.0.0.0
broadcast.address = 255.255.255.255
listen.address = 0.0.0.0:60001
timeout = 2.5s
; monitoring.healthcheck.interval = 15s
; monitoring.healthcheck.idle = 1m0s
; monitoring.healthcheck.ignore = 5m0s
; monitoring.watchdog.interval = 5s
card.format = any

# Wild Apricot
wild-apricot.http.client-timeout = 10s
wild-apricot.http.retries = 3
wild-apricot.http.retry-delay = 5s
wild-apricot.fields.card-number = FOB
; wild-apricot.fields.PIN = PIN
; wild-apricot.display-order.groups =
; wild-apricot.display-order.doors =
wild-apricot.facility-code = 43

UT0311-L0x.123456789.name = D123456789
UT0311-L0x.123456789.address = 192.168.1.250:60000
UT0311-L0x.123456789.door.1 = Front Door
UT0311-L0x.123456789.door.2 = Back Door
UT0311-L0x.123456789.door.3 = Unused3
UT0311-L0x.123456789.door.4 = Unused4
UT0311-L0x.123456789.timezone = UTC

```

Thanks,

**Comment by uhppoted** [comment] 2024-02-13 17:07
Oooops ... apologies - the README is wrong :-(. 

The _grules_ file should add the grant to the _permissions_ not the _record_:
```
// *** GRULES ***

rule Doors "Grants a member access to both doors" {
     when
         member.HasGroup("Doors")
     then
         permissions.Grant("Front Door");
         permissions.Grant("Back Door");
         permissions.Grant("Unused3");
         permissions.Grant("Unused4");
         Retract("Doors");
}

// *** END GRULES ***
```

Can you try that and let me know?

**Comment by bborncr** [comment] 2024-02-13 17:19
I made the changes but no changes regarding the ACL. Also, If I change "permissions" to anything else it doesn't show an error.

```
2024/02/13 17:12:43 INFO   Stashed downloaded 'grules' file to /var/uhppoted/wild-apricot.grl
MEMBERS:
  Name         Card Number Membership         Active Suspended Registered Expires    Board Members Doors Electronics Committee Laser Cutter Table Saw
  John Doe     11293050    Regular membership Y      N         2024-02-12 2024-03-11 N             Y     Y                     Y            Y
  Jane Doe     12345679    Regular membership Y      N         2024-02-12 2024-03-11 Y             Y     N                     Y            Y

DOORS:
  Back Door
  Front Door
  Unused3
  Unused4

ACL:
  Card Number From       To         Back Door Front Door Unused3 Unused4
  12345677    2024-01-01 2025-01-31 N         N          N       N
  12345679    2024-01-01 2025-01-31 N         N          N       N

```

**Comment by uhppoted** [comment] 2024-02-13 17:54
Hmmm .. werid, everything looks ok. Let me set up a test system that mirrors yours and see if I can replicate it.

**Comment by uhppoted** [comment] 2024-02-13 18:50
Hmmm - I've set up a test system that mirrors yours (except that my grules file revokes access to _Unused3_ and _Unused4_) and am getting the expected result:
```
./bin/uhppoted-app-wild-apricot --debug --config ../runtime/wild-apricot/uhppoted.conf get-acl --credentials ../runtime/wild-apricot/.credentials.json --rules ../runtime/wild-apricot/debug.grl
2024/02/13 10:40:23 INFO   Stashed downloaded 'grules' file to /usr/local/var/com.github.uhppoted/wild-apricot.grl
MEMBERS:
  Name     Card Number Membership         Active Suspended Registered Expires    Board Members Doors Electronics Committee Laser Cutter Table Saw
  Jane Doe 12345679    Regular membership Y      N         2024-02-12 2024-03-11 Y             Y     N                     Y            Y        
  John Doe 12345677    Regular membership Y      N         2024-02-12 2024-03-11 N             Y     Y                     Y            Y        

DOORS:
  Back Door
  Front Door
  Unused3
  Unused4

ACL:
  Card Number From       To         Back Door Front Door Unused3 Unused4
  12345677    2024-01-01 2025-01-31 Y         Y          N       N      
  12345679    2024-01-01 2025-01-31 Y         Y          N       N      
```

**Comment by uhppoted** [comment] 2024-02-13 18:51
Can you perhaps add some debugging to your grules file? e.g.
```
// *** GRULES ***

rule Doors "Grants a member access to both doors" {
     when
         member.HasGroup("Doors")
     then
         permissions.Grant("Front Door");
         permissions.Grant("Back Door");
         permissions.Revoke("Unused3");
         permissions.Revoke("Unused4");
         Retract("Doors");
}

rule Debug "Logs debug information" {
     when
         true
     then
         Log(">>>> DEBUG " + member.CardNumber);
         Log(">>>> DEBUG " + member.HasGroup("Doors"));
         Retract("Debug");
}

// *** END GRULES ***

```

**Comment by bborncr** [comment] 2024-02-13 20:01
I copy/pasted the above rules.

Output
```
sudo ./uhppoted-app-wild-apricot --debug --config uhppoted.conf  get-acl --credentials credentials.json --rules rules.conf
2024/02/13 19:55:46 INFO   Stashed downloaded 'grules' file to /var/uhppoted/wild-apricot.grl
MEMBERS:
  Name         Card Number Membership         Active Suspended Registered Expires    Board Members Doors Electronics Committee Laser Cutter Table Saw
  John Smith   11293051    Regular membership Y      N         2024-02-12 2024-03-11 N             Y     Y                     Y            Y
  Jane Smith   12345679    Regular membership Y      N         2024-02-12 2024-03-11 Y             Y     N                     Y            Y

DOORS:
  Back Door
  Front Door
  Unused3
  Unused4

INFO[0001] >>>> DEBUG 11293051                           lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG false                              lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG 12345679                           lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG false                              lib=grule-rule-engine package=AST source=GRL
ACL:
  Card Number From       To         Back Door Front Door Unused3 Unused4
  11293051    2024-01-01 2025-01-31 N         N          N       N
  12345679    2024-01-01 2025-01-31 N         N          N       N

  Card Number From       To         Back Door Front Door Unused3 Unused4
  11293051    2024-01-01 2025-01-31 N         N          N       N
  12345679    2024-01-01 2025-01-31 N         N          N       N

2024/02/13 19:55:46 INFO   Removing lockfile '/var/uhppoted/.wild-apricot/uhppoted-app-wild-apricot.lock'

```

**Comment by uhppoted** [comment] 2024-02-13 20:16
Ok, that helps - it thinks _Jane_ and _John_ aren't members of group _Doors_. Now to figure out why ... 

Can you run the `get-members` and `get-groups` commands:
```
sudo ./uhppoted-app-wild-apricot --debug --config uhppoted.conf  get-members --credentials credentials.json --file members.tsv
```
```
sudo ./uhppoted-app-wild-apricot --debug --config uhppoted.conf  get-groups --credentials credentials.json --file groups.tsv
```
and post the files here?

**Comment by uhppoted** [comment] 2024-02-13 20:17
And maybe add some more debugging to the grules file:
```
// *** GRULES ***

rule Doors "Grants a member access to both doors" {
     when
         member.HasGroup("Doors")
     then
         permissions.Grant("Front Door");
         permissions.Grant("Back Door");
         permissions.Revoke("Unused3");
         permissions.Revoke("Unused4");
         Retract("Doors");
}

rule Debug "Logs debug information" {
     when
         true
     then
         Log(">>>> DEBUG " + member.CardNumber);
         Log(">>>> DEBUG " + member.HasGroup("Doors"));
         Log(">>>> DEBUG " + member.Groups.Len());
         Retract("Debug");
}


// *** END GRULES ***
```

**Comment by bborncr** [comment] 2024-02-13 20:31
Members: It looks they are in the Doors group
```
Name          Card Number     Membership      Active  Suspended       Registered      Expires Board Members   Doors   Electronics Committee   Laser Cutter    Table Saw
John Smith    11293051        Regular membership      Y       N       2024-02-12      2024-03-11      N       Y       Y       Y       Y
Jane Smith    12345679        Regular membership      Y       N       2024-02-12      2024-03-11      Y       Y       N       Y       Y

```

Groups
```
ID      Groups
782239  Board Members
784869  Doors
784779  Electronics Committee
784771  Laser Cutter
784772  Table Saw

```

Output of `get-acl` with the added debug rules:
```
 sudo ./uhppoted-app-wild-apricot --debug --config uhppoted.conf  get-acl --credentials credentials.json --rules rules.conf
2024/02/13 20:28:14 INFO   Stashed downloaded 'grules' file to /var/uhppoted/wild-apricot.grl
MEMBERS:
  Name         Card Number Membership         Active Suspended Registered Expires    Board Members Doors Electronics Committee Laser Cutter Table Saw
  John Smith 11293051    Regular membership Y      N         2024-02-12 2024-03-11 N             Y     Y                     Y            Y
  Jane Smith   12345679    Regular membership Y      N         2024-02-12 2024-03-11 Y             Y     N                     Y            Y

DOORS:
  Back Door
  Front Door
  Unused3
  Unused4

INFO[0001] >>>> DEBUG 11293051                          lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG false                              lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG 4                                  lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG 12345679                           lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG false                              lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG 4                                  lib=grule-rule-engine package=AST source=GRL
ACL:
  Card Number From       To         Back Door Front Door Unused3 Unused4
  11293051    2024-01-01 2025-01-31 N         N          N       N
  12345679    2024-01-01 2025-01-31 N         N          N       N

  Card Number From       To         Back Door Front Door Unused3 Unused4
  11293051    2024-01-01 2025-01-31 N         N          N       N
  12345679    2024-01-01 2025-01-31 N         N          N       N

2024/02/13 20:28:14 INFO   Removing lockfile '/var/uhppoted/.wild-apricot/uhppoted-app-wild-apricot.lock'

```

**Comment by bborncr** [comment] 2024-02-13 20:59
Output works correctly with your credentials. Very strange.
```
2024/02/13 20:55:25 INFO   Stashed downloaded 'grules' file to /var/uhppoted/wild-apricot.grl
MEMBERS:
  Name     Card Number Membership         Active Suspended Registered Expires    Board Members Doors Electronics Committee Laser Cutter Table Saw
  Jane Doe 12345679    Regular membership Y      N         2024-02-12 2024-03-11 Y             Y     N                     Y            Y
  John Doe 12345677    Regular membership Y      N         2024-02-12 2024-03-11 N             Y     Y                     Y            Y

DOORS:
  Back Door
  Front Door
  Unused3
  Unused4

INFO[0001] >>>> DEBUG 12345679                           lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG true                               lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG 4                                  lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG 12345677                           lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG true                               lib=grule-rule-engine package=AST source=GRL
INFO[0001] >>>> DEBUG 4                                  lib=grule-rule-engine package=AST source=GRL
ACL:
  Card Number From       To         Back Door Front Door Unused3 Unused4
  12345677    2024-01-01 2025-01-31 Y         Y          N       N
  12345679    2024-01-01 2025-01-31 Y         Y          N       N

  Card Number From       To         Back Door Front Door Unused3 Unused4
  12345677    2024-01-01 2025-01-31 Y         Y          N       N
  12345679    2024-01-01 2025-01-31 Y         Y          N       N

```

**Comment by bborncr** [comment] 2024-02-13 21:34
I got it working by using the ID of the group instead of the name.
Thanks for your help!

**Comment by uhppoted** [comment] 2024-02-13 21:43
Ok, I see where the problem is - for some reason the group names returned with the member record don't match the actual group names:
```
11293050
[ 
  { 784771, Laser Cutter, 0},
  {784772, Table Saw, 0},
  {784779, Electronics Committee, 0},
  {784869, DoorAccess, 0},
]

12345679
[
  {782239, Board Members, 0},
  {784771, Laser Cutter, 0},
  {784772, Table Saw, 0},
  {784869, Door, 0},
]
```

Not entirely sure why - possibly you edited the _Doors_ group name after assigning it to the member and _Wild Apricot_ didn't carry it through because internally they only use the group ID.

You may be able to fix it from the Wild Apricot dashboard, but if not you can actually use the group ID in `HasGroup` e.g.:
```
// *** GRULES ***

rule Doors "Grants a member access to both doors" {
     when
         member.HasGroup(784869)
     then
         permissions.Grant("Front Door");
         permissions.Grant("Back Door");
         permissions.Revoke("Unused3");
         permissions.Revoke("Unused4");
         Retract("Doors");
}

// *** END GRULES ***
```

which is unambiguous and also won't break if people edit the group names (which they do for no good reason at all :-)) but is also harder to read. 

I'll have to think about maybe reworking the lookup logic - the assumption was that Wild Apricot would keep it consistent but clearly not.

**Comment by uhppoted** [comment] 2024-02-13 21:58
Oh, right - our replies crossed :-)

**Great**, very glad you've got it working! I'll add in some logic to make it a bit more robust and also easier to debug in future.

**Closed as completed** 2024-03-14 18:14 UTC
